### ISSUE TITLE
Performance (Upcoming) Blueprint

### ISSUE THREAD

**Issue by Thomoore** [PSUGraphicDesign/colevity#1]
Performance pages should include the following editable fields. This information will vary from one performance to the next.
- [x] Time
- [x] Date
- [x] Location
- [x] Brief Description
- [x] Price
- [x] Purchase Tickets
- [ ] Photo
- [ ] Video

**Comment by AugustMiller** [comment]
We've flattened performances into a single content type. No more separation between past and upcoming events.

In ce2a453e23c5e4439e9bdb77b2efa1d76da63427, I added the ability from the homepage blueprint to "Feature" an event, which is displayed above the navigation.
