### ISSUE TITLE
Issue with typography formatting

### ISSUE THREAD

**Issue by TJ-Butler** [PSUGraphicDesign/colevity#11]
Here are two problems that arose after I synced, not sure why they showed up like this:

![weird](https://cloud.githubusercontent.com/assets/11723377/7687954/a65e2178-fd55-11e4-9f08-2f53ccc1e1f3.png)
![weird2](https://cloud.githubusercontent.com/assets/11723377/7687953/a65c98a8-fd55-11e4-8be4-c033a5bd3816.png)

**Comment by AugustMiller** [comment]
Not really sure what the top image is showing… The type wraps sort of poorly, but I think it's as expected?

Second is definitely an issue. I'll track that down, today.
