### ISSUE TITLE
About Blueprint

### ISSUE THREAD

**Issue by jeburchett** [PSUGraphicDesign/colevity#2]
The About section will contain background information about CoLevity and its members. It will probably not need to be edited very frequently. Perhaps once a year or so when the group has new members. It should contain at least the following information.
- [ ] History/Formation: How they came together
- [ ] Mission Statement: Main goal of performances
- [ ] Tagline: Hilarity in Motion? We can’t change the world but we can change your mood?
- [ ] Photo
- [ ] Members
- [ ] _Name_
- [ ] _Bio: Who they are? Dance history? Short paragraph._
- [ ] _Photo_
- [ ] _Role/Title_

**Comment by liamphan** [comment]
Claimed!

**Comment by AugustMiller** [comment]
Done, as of 6df20ec4b0a182361ae48d59f0f8d5ca7f966226
