### ISSUE TITLE
Special Workshops Blueprint

### ISSUE THREAD

**Issue by TJ-Butler** [PSUGraphicDesign/colevity#3]
Important information to be included with blueprint for special workshops.

Special workshops differ from weekly classes in that they are occasional events that are not bound by a set weekly / monthly schedule.

_Special Workshops_
- [x] Title
- [x] Time
- [x] Dates
- [x] Description
- [x] Ability Level: Beginner, advanced
- [x] Age Range: Adult vs. Child
- [x] Pricing
- [x] Space available
- [x] Link to Reserve (Mindbody?)
- [x] Location
- [x] Teacher
- [ ] Photo

**Comment by TJ-Butler** [comment]
I'll take this one

**Comment by AugustMiller** [comment]
Any updates, @TJ-Butler? Push 'em if you got 'em!

**Comment by TJ-Butler** [comment]
Sorry @AugustMiller ! was unexpectedly busy this weekend, I'll get that pushed asap!

**Comment by TJ-Butler** [comment]
@AugustMiller blueprint for the workshops has been pushed. I wasn't sure how to add a photo field so I left that incomplete for now. Sorry again for the delay

**Comment by AugustMiller** [comment]
Done, as of 12a28b7ccd91c2c63d1e07acd11da511d2d5b072
