### ISSUE TITLE
Performance (Past) Blueprint

### ISSUE THREAD

**Issue by Thomoore** [PSUGraphicDesign/colevity#5]
This blueprint will be for pages that document past performances of CoLevity. It should include the following editable pages and is intended to be used as an archive of their performances only.
- [ ] Photos
- [ ] Videos
- [ ] Descriptions
- [ ] Reviews
- [ ] When it was performed (Month/Year)

**Comment by AugustMiller** [comment]
I think we should consider how this and the Upcoming performances blueprints can be combined…

My feeling is that the upcoming performances will be displayed differently, but don't really need to be different templates. Would they have to re-enter a performance once it's over?

PHP/Kirby are aware of the current date, so we can easily test whether an event is in the past or future, and display certain parts of the page differently, including any sort of feeds or lists that the event may appear in.

We can also test for the availability of information before trying to output it, so, for example, a past event that we can't get a ticketing URL for may say "Tickets are no longer available, but you're free to _attend another performance_ or _donate_!" when the URL field (that would ordinarily contain a link) is empty.
