### ISSUE TITLE
Contact Blueprint

### ISSUE THREAD

**Issue by liamphan** [PSUGraphicDesign/colevity#6]
The _Contact_ blueprint will contain information allowing the viewer to contact CoLevity through a variety of methods. Providing information such as address, phone, email, and further social networking links.
- [x] Email
- [x] Location
- [x] Phone Number
- [x] Hours of Contact
- [ ] Social Media Links
- [ ] Newsletter Signup
- [ ] Message Form

**Comment by Thomoore** [comment]
I'll create this blueprint.

**Comment by AugustMiller** [comment]
Made some updates to this in de672c47ddb84e0a5de7d1a0cb784d1c275bedb0, then added all the info to the homepage in 59a00712955f858f46e93bd60910885750d579b2.
