### ISSUE TITLE
Support Blueprint

### ISSUE THREAD

**Issue by jeburchett** [PSUGraphicDesign/colevity#7]
The Support blueprint will feature the following input fields. This information will probably not need to be edited very frequently, perhaps with volunteering positions or with the current sponsors. This page will probably be linked quite frequently throughout the website, as donations are super important.
- [ ] Donation form
- [ ] Tax ID
- [ ] Volunteering
- [ ] Plea for donations: Why we need it, how it’s used
- [ ] Photo
- [ ] Current/Ongoing Sponsors

**Comment by AugustMiller** [comment]
Going to build this now…

**Comment by AugustMiller** [comment]
Donation form won't really be a field, but there may be a link that has a specific label that activates the form.
